### ISSUE TITLE
Rename seg.largeArgFlag to seg.largeArcFlag

### ISSUE THREAD

**Issue by jarek-foksa** [motooka/SVGPathNormalizer#1]
Normalizer is always setting largeArcFlag to false due to this typo, which in turn breaks some test files such as: http://www.w3.org/Graphics/SVG/Test/20110816/harness/htmlObject/paths-data-03-f.html

**Comment by motooka** [comment]
@jarek-foksa Thank you for reporting this issue. It is now fixed and a new test case is added.
